source "https://rubygems.org"

gem "rails", "4.2.3"
gem "mysql2", "~> 0.3.18"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "jquery-ui-rails"
gem "ransack"
gem "devise"
gem "kaminari"
gem "bootstrap_form"
gem "bootstrap-kaminari-views"
gem "twitter-bootstrap-rails", ">= 2.0.3"
gem "cancancan"
gem "bootstrap-sass"
gem "jquery-turbolinks"
gem "rails_admin", :git => "git://github.com/sferik/rails_admin.git"
gem "toastr-rails"
gem "nprogress-rails"
gem "bootstrap-datepicker-rails"
gem "bootstrap-editable-rails"
gem "font-awesome-rails"
gem "hover-rails"
gem "sass-mediaqueries-rails"
gem "carrierwave"
gem "rails_admin_jcrop"
gem "paperclip"
gem "ckeditor"
gem "mini_magick"
gem "unicorn", "~> 5.0.1"
gem "factory_girl_rails"
gem "faker"
gem "meta-tags"

gem "sdoc", "~> 0.4.0", group: :doc

group :development, :test do
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "pry"
  gem "factory_girl_rails"
  gem "faker"
end

